import type { AnthropicCalibration } from "./anthropic.js";

// generated by `tokensift calibrate anthropic run` against a real Anthropic
// API key and a dedicated fixture corpus (test/fixtures/calibration/), not
// hand-tuned. Empty until that calibration run happens.
export const ANTHROPIC_CALIBRATIONS: Record<string, AnthropicCalibration> = {};
