import type { PricingRow } from "./pricing.js";

// Curated snapshot of LiteLLM's model pricing table, filtered to the models
// tokensift resolves an encoder for. Source: BerriAI/litellm (MIT), see
// LICENSE-THIRD-PARTY.md. Generated by scripts/update-pricing.mjs, not
// hand-tuned. Refresh with `pnpm pricing:update`.
//
// Snapshot date: 2026-07-24T09:15:47.493Z
export const PRICING_DATA: Record<string, PricingRow> = {
  "gpt-4o": {
    model: "gpt-4o",
    provider: "openai",
    inputCostPerToken: 0.0000025,
    outputCostPerToken: 0.00001,
    cacheReadInputCostPerToken: 0.00000125,
  },
  "gpt-4o-mini": {
    model: "gpt-4o-mini",
    provider: "openai",
    inputCostPerToken: 1.5e-7,
    outputCostPerToken: 6e-7,
    cacheReadInputCostPerToken: 7.5e-8,
  },
  "gpt-4.1": {
    model: "gpt-4.1",
    provider: "openai",
    inputCostPerToken: 0.000002,
    outputCostPerToken: 0.000008,
    cacheReadInputCostPerToken: 5e-7,
  },
  "gpt-4-turbo": {
    model: "gpt-4-turbo",
    provider: "openai",
    inputCostPerToken: 0.00001,
    outputCostPerToken: 0.00003,
  },
  "gpt-4": {
    model: "gpt-4",
    provider: "openai",
    inputCostPerToken: 0.00003,
    outputCostPerToken: 0.00006,
  },
  "gpt-3.5-turbo": {
    model: "gpt-3.5-turbo",
    provider: "openai",
    inputCostPerToken: 5e-7,
    outputCostPerToken: 0.0000015,
  },
  "claude-opus-4-5": {
    model: "claude-opus-4-5",
    provider: "anthropic",
    inputCostPerToken: 0.000005,
    outputCostPerToken: 0.000025,
    cacheReadInputCostPerToken: 5e-7,
  },
  "claude-sonnet-4-5": {
    model: "claude-sonnet-4-5",
    provider: "anthropic",
    inputCostPerToken: 0.000003,
    outputCostPerToken: 0.000015,
    cacheReadInputCostPerToken: 3e-7,
  },
  "claude-haiku-4-5": {
    model: "claude-haiku-4-5",
    provider: "anthropic",
    inputCostPerToken: 0.000001,
    outputCostPerToken: 0.000005,
    cacheReadInputCostPerToken: 1e-7,
  },
};
